### PR TITLE
Issue #8 just playing around with a new site

### PR DESCRIPTION
**Pull request by caprenter**
It's better than the version on the version2 branch so should be merged (into version2 NOT main)
I'm only putting it here as a pull request in case anyone else has been working on the version2 branch

Gets the about page configured
The front page has a minor update
Put the main navigation in an includes file
General messing about
Also trims the navigation menu
Leaves the contact page needing work

### CODE REVIEW

**Review by caffiendcode — APPROVED** [review]
- Code looks much neater
- About page doesn't look like it's fully wired together when I spin it up locally running with Ruby 2.7.2

**Comment by caprenter** [comment]
Can you post a screenshot @caffiendcode for what's not quite right.

I'm thinking I might press on with this version tomorrow. 

Appreciate your work. Thanks

**Comment by caprenter** [comment]
@caffiendcode So, I've had more time to play around today.

This is all working for me at the moment. 
I've added a csv file for the old films, but think we can probably just use the one csv file for all films and sort/order the data that we display.

I'm 99% of the way to saying this is V2 now. It needs a lot of files removing that we're not using.
And more work on images etc.

See if you can get it running and let me know what you think

**Comment by caprenter** [comment]
I'm merging all of this. I'm happy we've got a working version 2. It needs some tidying up and new issues creating to finish it up.

**Pull request merged**
